# Generated by Django 4.0.7 on 2023-03-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0003_alter_cart_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartproduct",
            name="product_count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
