# Generated by Django 4.0.7 on 2023-03-13 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorit_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorit_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
