# Generated by Django 4.0.7 on 2023-03-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
        ('favorits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritlist',
            name='favorit_products',
        ),
        migrations.AddField(
            model_name='favoritlist',
            name='favorit_products',
            field=models.ManyToManyField(related_name='favorit', to='products.product'),
        ),
    ]
