# Generated by Django 4.0.7 on 2023-03-13 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorits', '0002_remove_favoritlist_favorit_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritlist',
            name='favorit_products',
        ),
        migrations.AddField(
            model_name='favoritlist',
            name='favorite_products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
