# Generated by Django 4.0.7 on 2023-03-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
        ('favorits', '0003_remove_favoritlist_favorit_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritlist',
            name='product',
            field=models.ManyToManyField(related_name='favorite', to='products.product'),
        ),
    ]
