# Generated by Django 4.0.7 on 2023-03-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorits', '0005_alter_favoritlist_favorite_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritlist',
            old_name='favorite_products',
            new_name='user',
        ),
    ]
