# Generated by Django 4.0.7 on 2023-03-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("placed", "Placed"),
                            ("in progress", "In Progress"),
                            ("delivered", "Delivered"),
                        ],
                        default="placed",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
