# Generated by Django 4.0.7 on 2023-03-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_order",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
