# Generated by Django 4.0.7 on 2023-03-08 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0004_order_salesman"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="salesman",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salesman_product",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
