# Generated by Django 4.0.7 on 2023-03-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_order_salesman"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products_list",
            field=models.JSONField(default=dict),
        ),
    ]
