# Generated by Django 4.0.7 on 2023-03-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_URL',
            field=models.URLField(default='https://cdn1.staticpanvel.com.br/produtos/15/produto-sem-imagem.jpg'),
        ),
    ]
